### ISSUE TITLE
。。。

### ISSUE THREAD

**Issue by Jackieyewang** [Bytom/wiki#4]
你们中文白皮书和英文白皮书放反了

**Comment by zruijie** [comment]
没有吧，你指的是什么白皮书？连接能发过来吗？

**Comment by Jackieyewang** [comment]
https://github.com/Bytom/wiki/wiki

中文版打开是英文的，英文版打开是中文的，好像其他你们的白皮书比特币的UTXO模型可不可以多介绍一些。。。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Chengcheng Zhang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月12日(星期六) 下午2:17
收件人:&nbsp;"Bytom/wiki"<wiki@noreply.github.com&gt;;
抄送:&nbsp;"王业伟"<306981258@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Bytom/wiki] 。。。 (#4)




没有吧，你指的是什么白皮书？连接能发过来吗？

**Comment by zruijie** [comment]
我发现了，感谢你的反馈。

**Comment by zruijie** [comment]
技术运营马上修改。

**Comment by zruijie** [comment]
UTXO的全名是Unspend transaction output，中文意思即未花费的交易输出。在比原链上每一笔交易的每一个输入（issue, coinbase除外）都会消耗一个UTXO, 每一笔交易的每一个输出(retire除外)都会创造一个新的UTXO. 每一个比原的全节点都会维护个本地的UTXO池，为验证区块的流程提供UTXO合法性验证。在区块验证合法之后，节点会根据区块内的交易信息动态更新UTXO池。

在UTXO池中的存在形态是一个哈希，计算的方式是 SHA256（资产ID + 资产数量 + 智能合约 + SourceID）。 哈希中加入资产ID是因为比原链天然支持多资产，但在内核的设计中希望多资产共享一个UTXO池子所以加入资产ID用来混淆哈希。在UTXO的计算过程中资产数量，智能合约，与资产ID只是起到辅助混淆哈希结果的作用，真正保证了每一个UXTO的哈希的唯一性是依赖SourceID。SourceID是一笔交易所有输入的一个哈希，计算的方式是 SHA256（Input1 UTXO + Input2 UTXO … + InputN UTXO). 从高层级的视角来看SourceID可以代表一笔交易所有输入的历史转账数据，通过这种方式保证了每一个SourceID的唯一性。 每个SoureID的唯一性保障了每个UTXO的唯一性，每个UTXO的唯一性同时也逆向保障了每个SourceID的唯一性。

**Comment by Jackieyewang** [comment]
谢谢



------------------ 原始邮件 ------------------
发件人: "Chengcheng Zhang"<notifications@github.com>; 
发送时间: 2019年10月12日(星期六) 下午2:36
收件人: "Bytom/wiki"<wiki@noreply.github.com>; 
抄送: "王业伟"<306981258@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Bytom/wiki] 。。。 (#4)




UTXO的全名是Unspend transaction output，中文意思即未花费的交易输出。在比原链上每一笔交易的每一个输入（issue, coinbase除外）都会消耗一个UTXO, 每一笔交易的每一个输出(retire除外)都会创造一个新的UTXO. 每一个比原的全节点都会维护个本地的UTXO池，为验证区块的流程提供UTXO合法性验证。在区块验证合法之后，节点会根据区块内的交易信息动态更新UTXO池。
 
在UTXO池中的存在形态是一个哈希，计算的方式是 SHA256（资产ID + 资产数量 + 智能合约 + SourceID）。 哈希中加入资产ID是因为比原链天然支持多资产，但在内核的设计中希望多资产共享一个UTXO池子所以加入资产ID用来混淆哈希。在UTXO的计算过程中资产数量，智能合约，与资产ID只是起到辅助混淆哈希结果的作用，真正保证了每一个UXTO的哈希的唯一性是依赖SourceID。SourceID是一笔交易所有输入的一个哈希，计算的方式是 SHA256（Input1 UTXO + Input2 UTXO … + InputN UTXO). 从高层级的视角来看SourceID可以代表一笔交易所有输入的历史转账数据，通过这种方式保证了每一个SourceID的唯一性。 每个SoureID的唯一性保障了每个UTXO的唯一性，每个UTXO的唯一性同时也逆向保障了每个SourceID的唯一性。

**Comment by Jackieyewang** [comment]
我这边是万向区块链实验室，有机会可以合作




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Chengcheng Zhang"<notifications@github.com&gt;; 
发送时间: 2019年10月12日(星期六) 下午2:36
收件人: "Bytom/wiki"<wiki@noreply.github.com&gt;; 
抄送: "王业伟"<306981258@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Bytom/wiki] 。。。 (#4)




UTXO的全名是Unspend transaction output，中文意思即未花费的交易输出。在比原链上每一笔交易的每一个输入（issue, coinbase除外）都会消耗一个UTXO, 每一笔交易的每一个输出(retire除外)都会创造一个新的UTXO. 每一个比原的全节点都会维护个本地的UTXO池，为验证区块的流程提供UTXO合法性验证。在区块验证合法之后，节点会根据区块内的交易信息动态更新UTXO池。
 
在UTXO池中的存在形态是一个哈希，计算的方式是 SHA256（资产ID + 资产数量 + 智能合约 + SourceID）。 哈希中加入资产ID是因为比原链天然支持多资产，但在内核的设计中希望多资产共享一个UTXO池子所以加入资产ID用来混淆哈希。在UTXO的计算过程中资产数量，智能合约，与资产ID只是起到辅助混淆哈希结果的作用，真正保证了每一个UXTO的哈希的唯一性是依赖SourceID。SourceID是一笔交易所有输入的一个哈希，计算的方式是 SHA256（Input1 UTXO + Input2 UTXO … + InputN UTXO). 从高层级的视角来看SourceID可以代表一笔交易所有输入的历史转账数据，通过这种方式保证了每一个SourceID的唯一性。 每个SoureID的唯一性保障了每个UTXO的唯一性，每个UTXO的唯一性同时也逆向保障了每个SourceID的唯一性。

**Comment by zruijie** [comment]
你好，欢迎你们来合作，可以直接跟 contact@bytom.io  联系



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "王业伟"<notifications@github.com&gt;; 
发送时间: 2019年10月12日(星期六) 下午2:42
收件人: "Bytom/wiki"<wiki@noreply.github.com&gt;; 
抄送: "张成成"<943420582@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [Bytom/wiki] 。。。 (#4)



我这边是万向区块链实验室，有机会可以合作 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "Chengcheng Zhang"<notifications@github.com&amp;gt;;  
 发送时间: 2019年10月12日(星期六) 下午2:36 
 收件人: "Bytom/wiki"<wiki@noreply.github.com&amp;gt;;  
 抄送: "王业伟"<306981258@qq.com&amp;gt;; "Author"<author@noreply.github.com&amp;gt;;  
 主题: Re: [Bytom/wiki] 。。。 (#4) 
 
 
 
 
 UTXO的全名是Unspend transaction output，中文意思即未花费的交易输出。在比原链上每一笔交易的每一个输入（issue, coinbase除外）都会消耗一个UTXO, 每一笔交易的每一个输出(retire除外)都会创造一个新的UTXO. 每一个比原的全节点都会维护个本地的UTXO池，为验证区块的流程提供UTXO合法性验证。在区块验证合法之后，节点会根据区块内的交易信息动态更新UTXO池。 
   
 在UTXO池中的存在形态是一个哈希，计算的方式是 SHA256（资产ID + 资产数量 + 智能合约 + SourceID）。 哈希中加入资产ID是因为比原链天然支持多资产，但在内核的设计中希望多资产共享一个UTXO池子所以加入资产ID用来混淆哈希。在UTXO的计算过程中资产数量，智能合约，与资产ID只是起到辅助混淆哈希结果的作用，真正保证了每一个UXTO的哈希的唯一性是依赖SourceID。SourceID是一笔交易所有输入的一个哈希，计算的方式是 SHA256（Input1 UTXO + Input2 UTXO … + InputN UTXO). 从高层级的视角来看SourceID可以代表一笔交易所有输入的历史转账数据，通过这种方式保证了每一个SourceID的唯一性。 每个SoureID的唯一性保障了每个UTXO的唯一性，每个UTXO的唯一性同时也逆向保障了每个SourceID的唯一性。

**Comment by zruijie** [comment]
链接已更正，此 issue 将关闭
